apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-vaultkubenertes-job
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-vaultkubenertes-job
  chart:
    git: https://github.com/divyabhanu97/bevel.git
    ref: main
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: carrier
      component_type: peer
      namespace: carrier-net    
      images:
        alpineutils: vkycacr.azurecr.io/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://52.146.19.155:8200
      authpath: devcarrier-net-auth
      policy: vault-crypto-peer-carrier-net-ro
      secret_path: secret
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://bevelcluster-dns-8cdf394d.hcp.southeastasia.azmk8s.io:443
