apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: org3-vaultkubenertes-job
  namespace: org3-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: org3-vaultkubenertes-job
  chart:
    git: https://github.com/mrrancy/bevel
    ref: main
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: org3
      component_type: peer
      namespace: org3-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://20.43.156.77:8200
      authpath: devorg3-net-auth
      policy: vault-crypto-peer-org3-net-ro
      secret_path: secret
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://bevel-dev-dns-18636016.hcp.eastus.azmk8s.io:443
